In [2]:
import vectorbt as vbt
import pandas as pd
from datetime import datetime

from numba import njit
from vectorbt.utils.enum_ import map_enum_fields
from vectorbt.portfolio.enums import SizeType, Direction, NoOrder, OrderStatus, OrderSide
from vectorbt.portfolio import nb

In [3]:
def read_data_rsi(
    name: str,
    entries_lvl: int,
    exits_lvl: int,
    start_date: datetime.date,
    end_date: datetime.date
) -> pd.DataFrame:
    df = catalog.load(name)
    rsi = vbt.pandas_ta("RSI").run(df["close"], length=14)
    df['entries'] = rsi.rsi_crossed_below(entries_lvl).shift(1).fillna(False)
    df['exits'] = rsi.rsi_crossed_above(exits_lvl).shift(1).fillna(False)
    
    return df.loc[(df.index >= start_date) & (df.index <= end_date)]

In [9]:
df_vbt = read_data_rsi(
    name="GOOG_RSI", 
    entries_lvl=40, 
    exits_lvl=60, 
    start_date="2018-01-01", 
    end_date="2023-03-31"
)

[04/04/23 17:32:44] INFO     Loading data from 'GOOG_RSI' (ParquetDataSet)...                   ]8;id=932750;file://c:\Users\natta\anaconda3\envs\vbt-dvc\lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=722368;file://c:\Users\natta\anaconda3\envs\vbt-dvc\lib\site-packages\kedro\io\data_catalog.py#343\343]8;;\

In [10]:
df_vbt.loc[(df_vbt["entries"] == True)]

,open,high,low,close,RSI,RSI-based MA,Upper Bollinger Band,Lower Bollinger Band,entries,exits
time,,,,,,,,,,
2018-02-06T14:30:00Z,51.35900,54.085500,51.156835,54.0300,40.295697,70.245162,NaN,NaN,True,False
2018-02-08T14:30:00Z,52.77050,52.931000,50.033000,50.0760,28.058621,63.636056,NaN,NaN,True,False
2018-03-23T13:30:00Z,52.35150,53.168000,51.061000,51.0785,32.315122,51.239111,NaN,NaN,True,False
2018-03-28T13:30:00Z,49.90000,51.211500,49.032000,50.2280,33.744305,47.628408,NaN,NaN,True,False
2018-04-03T13:30:00Z,50.69550,51.049500,49.703500,50.6705,38.272574,42.827850,NaN,NaN,True,False
2018-04-09T13:30:00Z,50.84000,51.980000,50.704000,50.7725,40.367390,38.797446,NaN,NaN,True,False
2018-09-07T13:30:00Z,57.93350,58.763000,57.860750,58.2415,35.941415,49.317487,NaN,NaN,True,False
2018-09-13T13:30:00Z,58.53700,58.930500,58.142500,58.7665,42.247956,46.792190,NaN,NaN,True,False
2018-09-18T13:30:00Z,57.85450,58.804000,57.854500,58.0610,39.278527,42.974195,NaN,NaN,True,False
2018-10-08T13:30:00Z,57.50550,58.400000,56.368180,57.4485,37.573590,47.564259,NaN,NaN,True,False
2018-10-19T13:30:00Z,54.66850,55.518000,54.387500,54.8230,38.111680,38.536564,NaN,NaN,True,False
2018-10-25T13:30:00Z,53.58950,55.549000,53.477500,54.7785,43.002292,35.760807,NaN,NaN,True,False
2018-10-29T13:30:00Z,54.12350,54.852000,49.791500,51.0040,32.341168,35.678562,NaN,NaN,True,False
2018-11-06T14:30:00Z,51.97400,53.217250,51.903500,52.7905,42.371626,38.981477,NaN,NaN,True,False
2018-11-20T14:30:00Z,50.00000,51.587000,49.801000,51.2880,40.432185,43.155632,NaN,NaN,True,False
2018-12-24T14:30:00Z,48.69500,50.177000,48.505500,48.8110,34.556118,43.829508,NaN,NaN,True,False
2019-05-02T13:30:00Z,58.38800,58.709475,57.750090,58.1305,37.282347,63.472162,NaN,NaN,True,False
2019-05-09T13:30:00Z,57.95150,58.483000,57.542500,58.1190,39.141262,54.851757,NaN,NaN,True,False
2019-05-28T13:30:00Z,56.70000,57.579355,56.656000,56.7075,40.017226,40.654671,NaN,NaN,True,False
2019-05-30T13:30:00Z,55.77700,56.156500,55.606000,55.8975,36.842036,40.230250,NaN,NaN,True,False
2019-06-12T13:30:00Z,53.90000,54.046500,53.377000,53.8515,39.409078,35.305150,NaN,NaN,True,False
2019-10-03T13:30:00Z,59.00000,59.453000,58.121500,59.3915,43.462085,55.352951,NaN,NaN,True,False
2020-02-25T14:30:00Z,71.65000,71.907000,69.120000,69.4225,33.988221,59.474866,NaN,NaN,True,False
2020-03-04T14:30:00Z,67.96150,69.404500,67.155500,69.3260,44.070660,48.186805,NaN,NaN,True,False
2020-03-06T14:30:00Z,63.85300,65.311000,63.052500,64.9205,34.979112,43.809937,NaN,NaN,True,False
2020-03-26T13:30:00Z,55.59000,58.498500,54.676500,58.0875,44.332277,35.391223,NaN,NaN,True,False
2020-06-29T13:30:00Z,67.90900,69.780000,67.350500,69.7485,46.683227,55.382416,NaN,NaN,True,False
2020-09-21T13:30:00Z,72.00300,72.418000,70.327500,71.5580,34.132008,48.808471,NaN,NaN,True,False
2020-09-24T13:30:00Z,70.55150,72.185440,70.492500,71.4145,37.274043,42.132071,NaN,NaN,True,False
2021-09-29T13:30:00Z,137.10969,137.398500,134.250000,134.5210,33.811540,49.897253,NaN,NaN,True,False
2021-10-05T13:30:00Z,134.00000,137.362000,134.000000,136.1770,43.120552,44.297223,NaN,NaN,True,False
2022-01-06T14:30:00Z,137.49750,139.686000,136.763500,137.5510,32.764691,46.860446,NaN,NaN,True,False
2022-01-19T14:30:00Z,136.93850,138.399500,135.500000,135.6520,35.035203,40.540542,NaN,NaN,True,False
2022-02-22T14:30:00Z,129.98500,131.900750,127.741000,129.4025,38.433800,49.212434,NaN,NaN,True,False
2022-03-08T14:30:00Z,126.25050,131.246500,125.860750,127.2785,38.079498,43.649649,NaN,NaN,True,False
2022-04-12T13:30:00Z,132.42350,132.423500,127.576000,128.3745,36.097919,53.504163,NaN,NaN,True,False
2022-04-18T13:30:00Z,127.41000,128.712000,126.578465,127.9610,37.731576,48.647820,NaN,NaN,True,False
2022-04-21T13:30:00Z,129.35000,130.307500,124.650000,124.9375,35.615087,44.288354,NaN,NaN,True,False
2022-05-06T13:30:00Z,115.51900,117.498500,114.143000,115.6600,38.088304,36.925979,NaN,NaN,True,False
2022-05-19T13:30:00Z,111.84100,113.587500,110.468000,110.7455,36.789747,39.107037,NaN,NaN,True,False
2022-06-14T13:30:00Z,106.89000,108.457500,106.352000,107.1940,37.977296,45.554322,NaN,NaN,True,False
2022-06-17T13:30:00Z,106.53500,109.249500,105.628530,107.8655,41.435944,46.062161,NaN,NaN,True,False
2022-07-27T13:30:00Z,109.60000,114.400000,108.420000,113.6000,51.440538,48.499345,NaN,NaN,True,False
2022-08-29T13:30:00Z,110.78000,111.960000,109.810000,110.3400,38.519569,52.674855,NaN,NaN,True,False
2022-09-06T13:30:00Z,108.13500,108.880000,106.510000,107.4800,35.416194,44.100377,NaN,NaN,True,False
2022-09-14T13:30:00Z,105.44000,106.100000,104.500000,105.8700,37.398755,40.633873,NaN,NaN,True,False
2022-10-11T13:30:00Z,98.25000,100.120000,97.250000,98.0500,37.813946,36.368866,NaN,NaN,True,False
2022-10-17T13:30:00Z,99.52000,101.770000,99.510000,100.7800,47.245643,39.871685,NaN,NaN,True,False
2022-10-27T13:30:00Z,94.31000,95.170000,91.900000,92.6000,34.892102,44.111979,NaN,NaN,True,False
2022-11-02T13:30:00Z,90.91000,91.300000,87.010000,87.0700,31.817518,43.588490,NaN,NaN,True,False
2022-12-16T14:30:00Z,91.20000,91.750000,90.010000,90.8600,39.184932,48.312669,NaN,NaN,True,False
2022-12-28T14:30:00Z,87.50000,88.520000,86.370100,86.4600,34.607446,40.376152,NaN,NaN,True,False
2023-01-06T14:30:00Z,87.36000,88.470000,85.570000,88.1600,42.069421,39.247381,NaN,NaN,True,False
2023-02-27T14:30:00Z,90.09000,90.449900,89.610000,90.1000,39.736039,46.141144,NaN,NaN,True,False

In [11]:
df_vbt

,open,high,low,close,RSI,RSI-based MA,Upper Bollinger Band,Lower Bollinger Band,entries,exits
time,,,,,,,,,,
2018-01-02T14:30:00Z,52.4170,53.347000,52.261500,53.2500,61.294995,60.980591,NaN,NaN,False,False
2018-01-03T14:30:00Z,53.2155,54.314500,53.160500,54.1240,67.472431,61.584996,NaN,NaN,False,True
2018-01-04T14:30:00Z,54.4000,54.678495,54.200085,54.3200,68.679680,62.271872,NaN,NaN,False,False
2018-01-05T14:30:00Z,54.7000,55.212500,54.600000,55.1115,73.032453,63.026061,NaN,NaN,False,False
2018-01-08T14:30:00Z,55.1115,55.563500,55.081000,55.3470,74.182153,63.496636,NaN,NaN,False,False
...,...,...,...,...,...,...,...,...,...,...
2023-03-24T13:30:00Z,105.7400,106.160000,104.740000,106.0600,67.106101,57.212789,NaN,NaN,False,False
2023-03-27T13:30:00Z,105.3200,105.400000,102.630000,103.0600,59.347866,57.921012,NaN,NaN,False,False
2023-03-28T13:30:00Z,103.0000,103.000000,100.280000,101.3600,55.436663,58.271051,NaN,NaN,False,False
2023-03-29T13:30:00Z,102.7200,102.820000,101.030000,101.9000,56.419158,59.011712,NaN,NaN,False,False
2023-03-30T13:30:00Z,101.4400,101.610000,100.290000,101.3200,55.016145,59.893741,NaN,NaN,False,False